[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.22.0",
    "flask>=3.1.2",
    "pytelegrambotapi>=4.29.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
]
